all:
  children:

    production:
      children:

        nginx:
          hosts:
            web01:
              ansible_host: 10.0.1.11
            web02:
              ansible_host: 10.0.1.12
            web03:
              ansible_host: 10.0.1.13
            # ...
            # web50

        rabbitmq:
          hosts:
            rabbit01:
              ansible_host: 10.0.2.11
            rabbit02:
              ansible_host: 10.0.2.12
            rabbit03:
              ansible_host: 10.0.2.13
            # ...
            # rabbit50

###########################################
all:
  children:

    production:

      children:

        nginx:
          hosts:
            web01:
              ansible_host: 10.0.1.11
            web02:
              ansible_host: 10.0.1.12

        rabbitmq:
          hosts:
            rabbit01:
              ansible_host: 10.0.2.11
            rabbit02:
              ansible_host: 10.0.2.12

        ubuntu:
          hosts:
            web01:
            web02:
            rabbit01:
            rabbit02:

        rhel:
          hosts:
            web03:
            rabbit03: